### ISSUE TITLE
g2g not finding web site

### ISSUE THREAD

**Issue by JohnEngland65** [coder-alpha/G2Gfm.bundle#3]
G2g web site must of changed anyone else having issues?

**Comment by Oldpapa** [comment]
Yes.  Use f-movies. It has g2g as an option if I recall
Sent from Yahoo Mail on Android 
 
  On Sun, Sep 30, 2018 at 7:11 AM, JohnEngland65<notifications@github.com> wrote:   
G2g web site must of changed anyone else having issues?

**Comment by JohnEngland65** [comment]
working now site must have been down
